# Generated by Django 5.1.6 on 2025-02-27 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatreal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_env', models.DateTimeField(auto_now=True)),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinateur', to=settings.AUTH_USER_MODEL)),
                ('exped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expediteur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
